### ISSUE TITLE
Hello! and an updated on Audius Docs 🎧 

### ISSUE THREAD

**Issue by samgutentag** [emanuelpps/EPic-Sound#1]
Hello Emanuel!

Sam Gutentag here, Developer Relations at Audius.  Found your project here in GitHub and wanted to reach out and see if there is anythign I can do to help out integrating Audius?

Weve recently [revamped our Documentation](https://docs.audius.org/developers/introduction/overview) and are building up our [developer community in Discord](https://discord.gg/9QXRGJKm).

Happy Building! 🎧 

Sam

**Comment by emanuelpps** [comment]
Hi Sam! Thanks for reaching out to me. I was using the older documentation while building the project. Thanks for letting me know
